kumuluzee:
  name: picshare-imagemanagement
  version: 1.0.0
  server:
      base-url: http://localhost:8082/v1
      http:
        port: 8082
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/SimpleJdbcDS
      connection-url: jdbc:postgresql://localhost:5433/picshareimagemanagement
      username: postgres
      password: postgres
      max-pool-size: 20
  cors-filter:
      annotations:
        my-resource:
          allow-origin: "*"
          supported-methods: "GET, POST, DELETE, HEAD, OPTIONS"
          allow-subdomains: true
  health:
      servlet:
        mapping: /health
        enabled: true
      checks:
        data-source-health-check:
          jndi-name: jdbc/SimpleJdbcDS

microservice-mapping:
  storage: "http://localhost:8081/v1"
  userservice: "http://localhost:8080/v1"
  qr-api: "https://neutrinoapi-qr-code.p.rapidapi.com/qr-code"
  rapid-api-key: "fe76d007b5msh573d7c747a018d9p160cdajsn4e21704abffb"